apiVersion: apps/v1
kind: Deployment
metadata:
  name: coexistance-debug
spec:
  template:
    spec:
      containers:
        - name: coexistance
          volumeMounts:
            - name: server-source
              mountPath: /app/server/src
              readOnly: true
      volumes:
        - name: server-source
          hostPath:
            path: /Users/chris/sources/yoizen/acme/coexistance/app/server/src
            type: Directory
