apiVersion: v1
kind: ConfigMap
metadata:
  name: coexistance-config
  labels:
    app.kubernetes.io/name: coexistance
    app.kubernetes.io/component: webhook-debug
    app.kubernetes.io/part-of: yoizen-arch
data:
  PORT: "6666"
  NODE_ENV: "production"
  LOCAL_TESTING: "false"
  NATS_URL: "nats://nats.support-services-dev.svc.cluster.local:4222"
