apiVersion: v1
kind: Service
metadata:
  name: mongo-host
  labels:
    app.kubernetes.io/name: coexistance
    app.kubernetes.io/component: host-bridge
    app.kubernetes.io/part-of: yoizen-arch
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
