apiVersion: v1
kind: Service
metadata:
  name: coexistance-debug
  labels:
    app.kubernetes.io/name: coexistance
    app.kubernetes.io/component: webhook-debug
    app.kubernetes.io/part-of: yoizen-arch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: coexistance
    app.kubernetes.io/component: webhook-debug
  ports:
    - name: http
      port: 6666
      targetPort: http
      protocol: TCP
    - name: debug
      port: 9229
      targetPort: debug
      protocol: TCP
