---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tenant-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/scale-down-delay: "120s"
        autoscaling.knative.dev/window: "60s"
---


apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proxy-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/scale-down-delay: "120s"
        autoscaling.knative.dev/window: "60s"
---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: audit-service-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/scale-down-delay: "30s"
        autoscaling.knative.dev/window: "60s"
---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: usage-aggregator-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/scale-down-delay: "30s"
        autoscaling.knative.dev/window: "60s"
