apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local qa overlay. Mirrors cloud/qa scale-to-zero policy.

namespace: platform-services-qa

resources:
  - ../../../base

components:
  - ../../_components/scale-to-zero-non-prod

patches:
  - path: env-patches.yaml
