apiVersion: v1
kind: Namespace
metadata:
  name: support-services-dev
  labels:
    app.kubernetes.io/part-of: yoizen-arch
    yoizen.io/environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-services-dev
  labels:
    app.kubernetes.io/part-of: yoizen-arch
    yoizen.io/environment: dev
