import {
  IsBoolean,
  IsIn,
  IsNotEmpty,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  IsUrl,
  Length,
  Min,
} from "class-validator";

/**
 * Supported auth types for MCP servers (mcp-connections.md §2.1). Mirrors
 * `adapters.dto.ts`'s `ADAPTER_AUTH_TYPES` minus `oauth2-client` — OAuth2 is
 * an explicit non-goal for MCP servers in this phase (heavier, distinct
 * consent/token flow; revisit separately for both connector kinds).
 */
const MCP_SERVER_AUTH_TYPES = ["none", "api-key", "bearer", "basic"] as const;

export class CreateMcpServerDto {
  @IsString()
  @IsNotEmpty()
  @Length(1, 255)
  name!: string;

  @IsString()
  @IsOptional()
  description?: string;

  @IsString()
  @IsIn(["http", "sse"])
  transport_type!: "http" | "sse";

  @IsString()
  @IsNotEmpty()
  @IsUrl({ require_tld: false })
  url!: string;

  @IsObject()
  @IsOptional()
  headers?: Record<string, string>;

  @IsString()
  @IsOptional()
  @IsIn([...MCP_SERVER_AUTH_TYPES])
  authType?: "none" | "api-key" | "bearer" | "basic";

  /** Shape depends on `authType` (e.g. `{ headerName, key }` for `api-key`, `{ token }` for `bearer`, `{ username, password }` for `basic`); not validated per-shape here, same as `adapters.dto.ts`. */
  @IsObject()
  @IsOptional()
  authConfig?: Record<string, unknown>;

  @IsBoolean()
  @IsOptional()
  enabled?: boolean;

  // NOTE: `managed_by` is intentionally NOT exposed here — it is settable
  // only via the internal repository/service path (mcp-connections.md
  // §2.3), never via the public create DTO.
}

export class UpdateMcpServerDto {
  @IsString()
  @IsOptional()
  @Length(1, 255)
  name?: string;

  @IsString()
  @IsOptional()
  description?: string | null;

  @IsString()
  @IsOptional()
  @IsIn(["http", "sse"])
  transport_type?: "http" | "sse";

  @IsString()
  @IsOptional()
  @IsUrl({ require_tld: false })
  url?: string;

  @IsObject()
  @IsOptional()
  headers?: Record<string, string> | null;

  @IsString()
  @IsOptional()
  @IsIn([...MCP_SERVER_AUTH_TYPES])
  authType?: "none" | "api-key" | "bearer" | "basic";

  @IsObject()
  @IsOptional()
  authConfig?: Record<string, unknown> | null;

  @IsBoolean()
  @IsOptional()
  enabled?: boolean;
}

/**
 * Body for `POST admin/mcp-servers/usage-events` (mcp-connections.md §3).
 * Service-to-service only — called by `agent-ai-service`'s
 * `tool-bridge.service.ts` today (and, per §5.2, `connector-runtime`'s
 * `mcp-call.activity.ts` later) via `@yoizen/shared`'s `reportMcpUsageEvent`.
 * Not exposed through the admin-console/api-gateway proxy layer.
 */
export class RecordMcpUsageEventDto {
  /**
   * Idempotency key generated by the producer at the point the call was
   * measured (metering-foundation.md G4). Persisted as `mcp_call_events.id`
   * with `ON CONFLICT (id) DO NOTHING`, so a retried delivery of the same
   * call never double-inserts.
   */
  @IsString()
  @IsNotEmpty()
  eventId!: string;

  @IsString()
  @IsOptional()
  mcpServerId?: string;

  @IsString()
  @IsNotEmpty()
  serverName!: string;

  @IsString()
  @IsNotEmpty()
  toolName!: string;

  @IsBoolean()
  success!: boolean;

  @IsNumber()
  @Min(0)
  durationMs!: number;

  @IsString()
  @IsOptional()
  error?: string;

  /** Correlation id (e.g. conversation/workflow), when the producer has one (metering-foundation.md G5). */
  @IsString()
  @IsOptional()
  correlationId?: string;

  /** Causation id, when known. */
  @IsString()
  @IsOptional()
  causationId?: string;

  /** Agent/workflow execution id this call was made on behalf of, when known. */
  @IsString()
  @IsOptional()
  executionId?: string;
}
