export const MCP_USAGE_REPOSITORY = Symbol("MCP_USAGE_REPOSITORY");

/** A single MCP tool-call usage event (mcp-connections.md §3). */
export interface IRecordMcpUsageEventData {
  /**
   * Idempotency key generated by the producer at the point the call was
   * measured. Persisted as `mcp_call_events.id` with `ON CONFLICT (id) DO
   * NOTHING` (metering-foundation.md G4).
   */
  eventId: string;
  serverName: string;
  /** Resolved server id, when the caller (service) already knows it. */
  mcpServerId?: string | null;
  toolName: string;
  success: boolean;
  durationMs: number;
  error?: string | null;
  /** Correlation id (e.g. conversation/workflow), when the producer has one (metering-foundation.md G5). */
  correlationId?: string | null;
  /** Causation id, when known. */
  causationId?: string | null;
  /** Agent/workflow execution id this call was made on behalf of, when known. */
  executionId?: string | null;
}

/** One row of the "Recent calls" list (mcp-connections.md §6.3). */
export interface IMcpUsageRecentCall {
  toolName: string;
  success: boolean;
  durationMs: number;
  error: string | null;
  createdAt: Date;
}

/** Aggregate summary over the requested window, mirroring `IAdapterUsageRow`'s shape. */
export interface IMcpUsageSummary {
  totalCalls: number;
  successCalls: number;
  errorCalls: number;
  avgDurationMs: number;
}

export interface IMcpUsage {
  windowDays: number;
  summary: IMcpUsageSummary;
  recentCalls: IMcpUsageRecentCall[];
}

export interface IMcpUsageRepository {
  record(tenantId: string, data: IRecordMcpUsageEventData): Promise<void>;
  getUsage(
    tenantId: string,
    mcpServerId: string,
    windowDays: number,
    recentLimit: number
  ): Promise<IMcpUsage>;
}
