apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme-dev-ns

resources:
  - ../../base
  - mongo-credentials.yaml

patches:
  - path: runtime-mongo-env.yaml
    target:
      kind: Service
      name: yoizenclaw-runtime
