apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb-image-catalog.yaml
  - postgres-shared-cluster.yaml
  - postgres-usage-shared-cluster.yaml
  - postgres-temporal-cluster.yaml
  - postgres-temporal-visibility-cluster.yaml
  - poolers.yaml
  - configmap.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml
