apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

patches:
  - path: patches/nats-resources.yaml
  - path: patches/nats-config.yaml
  - path: patches/redis-resources.yaml
  - path: patches/postgres-resources.yaml
  - path: patches/postgres-temporal-resources.yaml
  - path: patches/observability-resources.yaml
