/**
 * Shared shape for MCP tool-call usage events (mcp-connections.md §3).
 *
 * Producer-agnostic on purpose: `agent-ai-service`'s `tool-bridge.service.ts`
 * is the first producer (agent chat execution path), and `connector-runtime`'s
 * future `mcp-call.activity.ts` (mcp-connections.md §5.2) is a planned second
 * producer (workflow execution path). Both report the same shape to the same
 * `agent-admin-service` write endpoint, which owns the `mcp_call_events`
 * table (it already owns `mcp_servers`, in the same per-tenant database).
 */
export interface IMcpUsageEvent {
  /**
   * Idempotency key for this call event, generated by the caller at the
   * point the MCP call is measured (one UUID per tool invocation). Written
   * as `mcp_call_events.id` with `ON CONFLICT (id) DO NOTHING` so a retried
   * delivery (client-side retry here, or a redelivered Temporal activity)
   * never double-inserts the same call (metering-foundation.md G4).
   */
  readonly eventId: string;
  /** Tenant scope. */
  readonly tenantId: string;
  /**
   * MCP server row id, when the caller already knows it (e.g.
   * `connector-runtime` resolves the server by id before calling a tool).
   * Omit when only the server name is known (e.g. agent-ai-service's live
   * connection registry is keyed by name) — the write endpoint resolves the
   * id server-side on a best-effort basis.
   */
  readonly mcpServerId?: string;
  /** MCP server name, as configured on the `mcp_servers` row. */
  readonly serverName: string;
  /** Name of the tool that was called. */
  readonly toolName: string;
  /** Whether the tool call succeeded. */
  readonly success: boolean;
  /** Wall-clock duration of the tool call, in milliseconds. */
  readonly durationMs: number;
  /** Error message, when `success` is `false`. */
  readonly error?: string;
  /**
   * Correlation id for the broader unit of work this call belongs to
   * (e.g. the conversation/workflow execution), when the producer has one
   * (metering-foundation.md G5). Nullable — genuinely absent for some
   * producers/paths.
   */
  readonly correlationId?: string;
  /** Causation id (the event/action that directly triggered this call), when known. */
  readonly causationId?: string;
  /** Id of the agent/workflow execution this call was made on behalf of, when known. */
  readonly executionId?: string;
}
