apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MONGO_DB: yoizen
  MONGO_USER: yoizen
  MONGO_PASSWORD: yoizen-dev-password
