apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
      protocol: TCP
    - name: monitor
      port: 8222
      targetPort: monitor
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
      protocol: TCP
