"""YoizenClaw OpenTelemetry metrics (wdocs/06 compliance).

Provides counters and histograms for ingress, agent events,
depth violations, claim check, and runtime heartbeats.
All metric names use the ``yoizenclaw.*`` prefix per
wdocs/06-observabilidad.md.
"""

from __future__ import annotations

from opentelemetry import metrics

# ---------------------------------------------------------------------------
# Module-level metric instruments — populated by ``initialize()``.
# Callers should use the ``record_*`` helpers rather than accessing
# these variables directly.
# ---------------------------------------------------------------------------

ingress_published: metrics.Counter | None = None
ingress_publish_failed: metrics.Counter | None = None
ingress_publish_latency_ms: metrics.Histogram | None = None
agent_events: metrics.Counter | None = None
agent_depth_exceeded: metrics.Counter | None = None
claimcheck_stored: metrics.Counter | None = None
claimcheck_inline: metrics.Counter | None = None
runtime_heartbeat: metrics.Counter | None = None


def initialize(meter: metrics.Meter | None = None) -> None:
    """Create (or recreate) all YoizenClaw metric instruments.

    In production this is called once at startup.  In tests it can be
    called repeatedly to rebind the instruments to a test meter backed
    by an ``InMemoryMetricReader``.

    Args:
        meter: Optional pre-built ``Meter``.  When *None* the default
            meter named ``"yoizenclaw"`` is obtained from the global
            ``MeterProvider``.
    """
    global ingress_published, ingress_publish_failed
    global ingress_publish_latency_ms, agent_events
    global agent_depth_exceeded, claimcheck_stored
    global claimcheck_inline, runtime_heartbeat

    _meter = meter or metrics.get_meter("yoizenclaw")

    ingress_published = _meter.create_counter(
        "yoizenclaw.ingress.published",
        description="Events published successfully",
        unit="1",
    )

    ingress_publish_failed = _meter.create_counter(
        "yoizenclaw.ingress.publish_failed",
        description="Failed publishes to NATS",
        unit="1",
    )

    ingress_publish_latency_ms = _meter.create_histogram(
        "yoizenclaw.ingress.publish_latency_ms",
        description="Latency of publish operations",
        unit="ms",
    )

    agent_events = _meter.create_counter(
        "yoizenclaw.agent.events",
        description="Events generated by agents",
        unit="1",
    )

    agent_depth_exceeded = _meter.create_counter(
        "yoizenclaw.agent.depth_exceeded",
        description="Events rejected by depth limit",
        unit="1",
    )

    claimcheck_stored = _meter.create_counter(
        "yoizenclaw.claimcheck.stored",
        description="Payloads stored in Object Store",
        unit="1",
    )

    claimcheck_inline = _meter.create_counter(
        "yoizenclaw.claimcheck.inline",
        description="Payloads that traveled inline",
        unit="1",
    )

    runtime_heartbeat = _meter.create_counter(
        "yoizenclaw.runtime.heartbeat",
        description="Runtime heartbeats sent",
        unit="1",
    )


# ---------------------------------------------------------------------------
# Convenience record helpers
# ---------------------------------------------------------------------------


def record_ingress_published(tenant: str, subject: str) -> None:
    """Record a successfully published ingress event.

    Args:
        tenant: Tenant identifier.
        subject: NATS subject the event was published to.
    """
    if ingress_published is not None:
        ingress_published.add(1, {"tenant": tenant, "subject": subject})


def record_ingress_publish_failed(tenant: str, reason: str) -> None:
    """Record a failed ingress publish.

    Args:
        tenant: Tenant identifier.
        reason: Failure reason (e.g. ``"invalid_envelope"``).
    """
    if ingress_publish_failed is not None:
        ingress_publish_failed.add(1, {"tenant": tenant, "reason": reason})


def record_ingress_publish_latency(latency_ms: float, tenant: str) -> None:
    """Record ingress publish latency.

    Args:
        latency_ms: Publish latency in milliseconds.
        tenant: Tenant identifier.
    """
    if ingress_publish_latency_ms is not None:
        ingress_publish_latency_ms.record(latency_ms, {"tenant": tenant})


def record_agent_event(agent_id: str, event_type: str, tenant: str) -> None:
    """Record an agent-generated event.

    Args:
        agent_id: Agent identifier.
        event_type: Event type (e.g. ``"outbound"``).
        tenant: Tenant identifier.
    """
    if agent_events is not None:
        agent_events.add(
            1,
            {"agent_id": agent_id, "event_type": event_type, "tenant": tenant},
        )


def record_depth_exceeded(tenant: str, depth: int) -> None:
    """Record a depth-limit violation.

    Args:
        tenant: Tenant identifier.
        depth: The depth value that exceeded the limit.
    """
    if agent_depth_exceeded is not None:
        agent_depth_exceeded.add(1, {"tenant": tenant, "depth": str(depth)})


def record_claimcheck_stored(tenant: str, size_bytes: int) -> None:
    """Record a payload stored via claim check.

    Args:
        tenant: Tenant identifier.
        size_bytes: Payload size in bytes.
    """
    if claimcheck_stored is not None:
        claimcheck_stored.add(
            1, {"tenant": tenant, "size_bytes": str(size_bytes)}
        )


def record_claimcheck_inline(tenant: str, size_bytes: int) -> None:
    """Record a payload that traveled inline.

    Args:
        tenant: Tenant identifier.
        size_bytes: Payload size in bytes.
    """
    if claimcheck_inline is not None:
        claimcheck_inline.add(
            1, {"tenant": tenant, "size_bytes": str(size_bytes)}
        )


def record_runtime_heartbeat(tenant: str, status: str) -> None:
    """Record a runtime heartbeat.

    Args:
        tenant: Tenant identifier.
        status: Heartbeat status (e.g. ``"healthy"``).
    """
    if runtime_heartbeat is not None:
        runtime_heartbeat.add(1, {"tenant": tenant, "status": status})


# ---------------------------------------------------------------------------
# Auto-initialize on first import with the global MeterProvider.
# In tests, ``initialize()`` is called again with a test meter.
# ---------------------------------------------------------------------------
initialize()
